name: Build Program
run-name: ${{ github.actor }} is building the program 🛠️
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Apply automatic formatting
        run: make format

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i --verbose && git diff --exit-code

      - name: Build application
        run: make

      - name: Build & run tests
        run: make test
